# Project information
site_name: What I learned today (@rohancragg)
site_description: '@rohancragg''s Personal Tech Docs'
site_author: 'Rohan Cragg'
site_url: 'https://rohancragg.co.uk/'
fb_appid: '245640346829400'

# Page tree
nav:
  - Home: README.md
  - About Me: about.md
  - Tools & Techniques:
    - Scoop & Co: misc\scoop.md
    - Bash Shell on Windows: misc\git-bash.md
    - Miscellanous Notes: misc\misc.md
  - DevOps:
    - Azure DevOps - Self-Hosted Build Agents: devops\azdo-self-hosted-build-agents.md
    - VM Patching in DevTest Labs: compute\patching-devtestlabs.md
  - Kubernetes:
    - Clusters and Domains: aks\domains.md
    - Create a TLS Secret: aks\create-tls-secret.md
  - Writing:
    - Prettier link sharing with MkDocs: writing\social-media-sharing.md

# Repository
repo_name: 'rohancragg/blog-notes'
repo_url: 'https://github.com/rohancragg/blog-notes'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Rohan Cragg'

# Configuration
theme:
  name: material
  language: 'en'
  custom_dir: 'theme'
  palette:
    primary: 'deep purple'
    accent: 'green'
  font:
    text: 'Noto Sans'
    code: 'Ubuntu Mono'
  features:
    - tabs
    - instant
  icon:
    logo: material/library

# Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
  - git-revision-date
  - minify:
      minify_html: false
      
# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/rohancragg'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/rohancragg'
    - icon: fontawesome/brands/github
      link: 'https://github.com/rohancragg'
    - icon: fontawesome/brands/facebook
      link: 'https://fb.com/rohancragg'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/rohancragg/'
    - icon: fontawesome/solid/terminal
      link: 'https://asciinema.org/~rohancragg'
  disqus: 'rohancragg'
  theme:
    icon:
      repo: fontawesome/brands/gitlab

extra_javascript:
  - 'https://platform.linkedin.com/badges/js/profile.js'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: rohancragg
      repo: blog-notes
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown